name: Pre-Release

on:
  push:
    branches: ["ci/test_build_test"]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  test_rust:
    name: Test Rust
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - run: git submodule update --init --recursive

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build and Test
        uses: actions-rs/cargo@v1
        with:
          command: test
